name: Issue Closer

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  issue-closer:
    runs-on: ubuntu-latest
    steps:
    - uses: nischalstha9/issue-closer@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repo: ''
        base_branch: ''


